version: '3.8'

services:
  api:
    build: .
    container_name: recette_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: recette_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
